---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: build-out-repo
- name: current-app-info

outputs:
- name: output

run:
  path: build-out-repo/ci/tasks/app-manifest-prep-canary
