---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: localhost:5000/pivotalservices/docker-concourse-cf-tools
    tag: "latest"
    insecure_registries: [ "localhost:5000" ]
     
    

inputs:
- name: build-out-repo
- name: current-app-info

outputs:
- name: output

run:
  path: build-out-repo/ci-offline/tasks/app-manifest-prep
