---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfservices/docker-concourse-cf-tools
    tag: "latest"

run:
  path: concourse-pipeline-samples/docker-image-update/ci/tasks/dummy-task.sh
