---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: localdockerrepo.pcfdemo.net:5000/java
    tag: 8-jdk-alpine
    insecure_registries: [ "localdockerrepo.pcfdemo.net:5000" ]

inputs:
- name: articulate-ci-demo


run:
  path: articulate-ci-demo/ci-offline/tasks/run-unit-tests
