---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: demo-repo

outputs:
- name: current-app-info

run:
  path: demo-repo/ci/tasks/current-app-get-info-canary
