---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: djudorange/node-gulp-mocha
    tag: "latest"

inputs:
- name: articulate-ci-demo
- name: current-app-info

run:
  path: articulate-ci-demo/ci/tasks/load-tests
