---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine

inputs:
- name: articulate-ci-demo


run:
  path: articulate-ci-demo/ci/tasks/run-unit-tests
