---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: demo-repo
- name: current-app-info

run:
  path: demo-repo/ci/tasks/update-routes-canary
